### ISSUE TITLE
TypeError: list indices must be integers, not str

### ISSUE THREAD

**Issue by Hibou57** [acrisci/i3ipc-python#21] opened 2015-12-20 21:34 UTC
I had this error from `i3ipc.py`: “TypeError: list indices must be integers, not str”

Seems to be from an `__init__` invoked from `get_tree`, so I guess this is the `__init__` of `Con`.

**Comment by acrisci** [comment] 2015-12-20 21:48
Can you give me a complete stack trace and steps to reproduce?

**Comment by Hibou57** [comment] 2015-12-20 23:48
Hard to reproduce. I can just reproduce an error which gives me this trace:

    InterruptedError:
        4
        Interrupted system call

    /home/yannick/apps/python3/lib/python3.4/site-packages/i3ipc.py:213: in _ipc_recv
    /home/yannick/apps/python3/lib/python3.4/site-packages/i3ipc.py:227: in _ipc_send
    /home/yannick/apps/python3/lib/python3.4/site-packages/i3ipc.py:231: in message
    /home/yannick/apps/python3/lib/python3.4/site-packages/i3ipc.py:265: in get_tree

May be the previous type error was related?

I'm still trying to reproduce it.

**Comment by Hibou57** [comment] 2015-12-20 23:51
Indeed. I most of time getting the above, while fewer times, getting this one:

    TypeError: list indices must be integers, not str

    /home/yannick/apps/python3/lib/python3.4/site-packages/i3ipc.py:415: in __init__
    /home/yannick/apps/python3/lib/python3.4/site-packages/i3ipc.py:266: in get_tree

May be this type error is a result of an interrupted system call?

**Comment by Hibou57** [comment] 2015-12-21 00:35
If I do this:

    while True:
        try:
            root = I3.get_tree()
            break
        except InterruptedError:
            continue

and if it's interrupted, then I get the type error as in the prior message.

**Comment by Hibou57** [comment] 2015-12-21 01:25
For now, here are two work‑around I'm using (where `I3` is a global):

    def i3_get_tree():
        result = None
        while True:
            try:
                result = I3.get_tree()
                break
            except InterruptedError:
                continue
            except TypeError:
                continue
        return result


    def i3_command(command):
        while True:
            try:
                I3.command(command)
                break
            except InterruptedError:
                continue

**Comment by acrisci** [comment] 2015-12-21 02:17
What i3 version are you using? Use `i3 --version`.

**Comment by Hibou57** [comment] 2015-12-21 03:54
For i3WM:

    $ i3 --version
    > i3 version 4.11 (2015-09-30, branch "4.11") © 2009 Michael Stapelberg and contributors

For Python 3:

    $ python3 --version
    > Python 3.4.3

**Comment by acrisci** [comment] 2015-12-22 18:39
So it seems the data from the tree is being passed as a list instead of a dict when the Con is initted. I have no idea how this could happen. It would be interesting to see what the value of `data` is in the `__init__` method of the Con.

I don't think I can work on this without steps to reproduce it.

**Comment by Pikaro** [comment] 2018-11-01 12:21
I just had this happen when I was working with threading. One thread initiated a workspace change, the second subscribed to focus events and fetched the tree after one. Looks like the listener thread saw the [{success: True}] from the workspace change command. Easily fixed by using separate IPC connections per thread, but maybe something similar happened here.

**Comment by acrisci** [comment] 2018-11-01 12:29
I don't doubt there's a bug here, but I don't think that's it. We use a separate socket connection for commands and events to prevent that. Also, the ipc tells us what kind of event it is in a message header.

**Comment by Pikaro** [comment] 2018-11-01 13:04
```
#!/usr/bin/python3

from threading import Thread
import i3ipc
import sys
from time import sleep

class A(Thread):
    def __init__(self, con):
        Thread.__init__(self)
        self.con = con
        self.con.on('window::focus', self.cb)

    def run(self):
        i3 = Thread(target=self.con.main)
        i3.start()

    def cb(self, event, frame):
        self.con.get_tree()
        sys.exit(0)

class B(Thread):
    def __init__(self, con):
        Thread.__init__(self)
        self.con = con

    def run(self):
        self.con.command('workspace 1:Web')

con = i3ipc.Connection()

a = A(con)
a.start()
sleep(1)
b = B(con)
b.start()
sleep(1)
```

1:Web has only a windowed Firefox window with a 1px border. This has three outcomes for me:

- It works (usually)
- This: (The exact string it trips over changes - it looks like it's a few bytes forward or back in a data stream?)
```
i3-ipc�|{"id
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/vinter/test.py", line 28, in run
    self.con.command('workspace 1:Web')
  File "/usr/local/lib/python3.6/dist-packages/i3ipc/i3ipc.py", line 426, in command
    return json.loads(data, object_hook=CommandReply)
  File "/usr/lib/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
- This:
```
[{'success': True}]
Error data: ]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/i3ipc/i3ipc.py", line 528, in get_tree
    return Con(json.loads(data), None, self)
  File "/usr/local/lib/python3.6/dist-packages/i3ipc/i3ipc.py", line 892, in __init__
    self.rect = Rect(data['rect'])
TypeError: list indices must be integers or slices, not str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/i3ipc/i3ipc.py", line 649, in main
    while not self.event_socket_poll():
  File "/usr/local/lib/python3.6/dist-packages/i3ipc/i3ipc.py", line 639, in event_socket_poll
    self._pubsub.emit(event_name, event)
  File "/usr/local/lib/python3.6/dist-packages/i3ipc/i3ipc.py", line 287, in emit
    s['handler'](self.conn, data)
  File "/home/vinter/test.py", line 19, in cb
    self.con.get_tree()
  File "/usr/local/lib/python3.6/dist-packages/i3ipc/i3ipc.py", line 531, in get_tree
    print("Error data byes: " + "".join("{:02x}".format(ord(c)) for c in s))
NameError: name 's' is not defined
```

print(data)s added in i3ipc.py in these two places to see the error data. You might want to let this or something similar in an automated way overnight and only log the errors because with this example it works like 90% of the time. With my full application, it was much more reproducible.

**Comment by acrisci** [comment] 2018-11-01 14:44
Ah ok that example makes the issue pretty clear.

The `con.get_tree()` and the `con.command()` are accessing the same socket at the same time. I just need add a lock on socket access to make the command thread safe.

**Comment by acrisci** [comment] 2018-11-01 15:03
I just pushed e9fcefa and I can't reproduce the error anymore with that example.

**Comment by Pikaro** [comment] 2018-11-01 15:06
Great! No idea if that was the original issue, but that's at least one error case less.

**Comment by Hibou57** [comment] 2018-11-01 16:08
@Pikaro , I can’t tell now neither if it’s the same as the original issue, I will test it a future day (I will first have to retrieve the original script from four years ago).

**Closed** 2019-06-24 14:09 UTC
